# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT += widgets
TEMPLATE = app
TARGET = TodoList
DESTDIR = ./x64/Release
CONFIG += release
LIBS += -L"."
PRECOMPILED_HEADER = stdafx.h
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(TodoList.pri)
win32:RC_FILE = TodoList.rc
RC_ICONS = TodoLists.ICON
